version: 1
  sources:
      - name: business_data_shared
      project: business_analytics_data
      dataset: business_data_shared
      tables:
        - name: device_type
        - name: top_10_stores
        - name: churn
        - name: average_amount
        - name: fraud_rate
        - name: top_10_products
        - name: … <other tables>
