version: 1

  models:
    - name: bl_first_five_transactions
      meta:
        owners:
          - ‘Analytics’
          - ‘Data Science’
      config:
        tags: bl_first_five_transactions
        partition_by:
          field: happened_at
          data_type: date
          granularity: day
