version: 1

  models:
    - name: ml_store_kpis
      meta:
        owners:
          - ‘Data Engineering’
      config:
        tags: ml_store_kpis
        partition_by:
          field: created_at
          data_type: date
          granularity: day
        materialized: incremental
        incremental_strategy: insert_overwrite
